### ISSUE TITLE
TensorBoard stuck at 'Loading..'

### ISSUE THREAD

**Issue by priyankahubli** [MaxSobolMark/HardRLWithYoutube#1]
After training, when I try to visualize the embeddings on the tensorboard,
the tensorboard fails to load the data and is stuck at this:

![image](https://user-images.githubusercontent.com/32818042/52068819-68a61300-254b-11e9-99be-2a1bfcdb2b14.png)

I am running it on TensorBoard 1.12.0

**Comment by MaxSobolMark** [comment]
@priyankahubli it seems like it's not finding the checkpoint for the embeddings. Did you run visualize_embeddings to generate the embedding files?
