### ISSUE TITLE
How are about performance on montezuma?

### ISSUE THREAD

**Issue by CrazySssst** [MaxSobolMark/HardRLWithYoutube#3]

**Comment by MaxSobolMark** [comment]
When I ran it I got at most the first actual reward from the Montezuma environment (and not the imitation reward,) but then it got stuck there. Keep in mind that this was run with much less parallel actors than the original paper (8 vs 100) and for a very short time, so it might not be representative of the best possible performance given more resources.

If you're asking about the original paper, they achieved much higher than human results.
