### ISSUE TITLE
Why did I come to 'mmco:unref short failure' and print this ValueError: 'Empty range for randrange()' 

### ISSUE THREAD

**Issue by kynehc** [MaxSobolMark/HardRLWithYoutube#4]
I followed the procedure to download videos. After that when I tried to train the featurizer, it happened this.
![image](https://user-images.githubusercontent.com/18049905/56505108-3f46c300-654d-11e9-8e5f-76ad49e9d0fe.png)
I tried to figure out why occurred to this error.
![image](https://user-images.githubusercontent.com/18049905/56505166-6dc49e00-654d-11e9-9e3e-a7165ab8a670.png)
this means Video1 and Video3 can't successfully preprocess and only Video2 to train the featurizer.

And after I found that empty range error due to this code in TDC model, which as said in the paper.
![image](https://user-images.githubusercontent.com/18049905/56505511-77023a80-654e-11e9-8157-a83138c0d65b.png)
after I changed this possible_frames_end to 80 from 200, It trains the featurizer successfully but by only Video2.
![image](https://user-images.githubusercontent.com/18049905/56505854-5a1a3700-654f-11e9-88e4-9d82e790e256.png)

So what should I do to solve this? Thanks!

**Comment by MaxSobolMark** [comment]
The error seems to be the length of the videos. Every video should have much more than 200 frames, so this shouldn't be a problem if they are downloaded correctly.

The error is in line 218, calling random.randint with a negative parameter, and that would only happen if videos[video_index].shape[0] < 200.

Try to download the videos again, and also check videos[video_index].shape[0] to make sure it's more than 200.

**Comment by kynehc** [comment]
I downloaded the videos by the given download_videos.py
python download_videos.py --filename montezuma.txt
I have tried many times and it’s same. And Video1 and 3 can’t preprocess due to the error  “unref short failure”.

**Comment by kynehc** [comment]
Can u share your version of python, opencv, scipy, tensorflow? I will try to recovery the same development environment.

**Comment by MaxSobolMark** [comment]
You can use this environment for testing: https://colab.research.google.com/drive/1pKFO8hUpOZv_KZetEXmvxoNfyIoO9uQj

Everything up to the PPO part should be working. For the PPO part I had to run it locally.

**Comment by kynehc** [comment]
Thanks, I run it successfully. 
But the performance seems like not good, would u share your saved model after ppo2, so I can run it locally to see the good results.

**Comment by MaxSobolMark** [comment]
Unfortunately, I don't have access to my previously trained ppo2 model. However, you could try to make PPO work on the colab. There seem to be some problems with updated packages, but that might be not too hard to fix. And performance on Google colab is very good, it shouldn't take too long to train the model.
